using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Identity;

namespace PADatabase.Models;

public class Course
{

    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)] // Indicates that the value is generated by the database
    public Guid Id { get; set; }

    public string Name { get; set; }
    public string? Description { get; set; }
    public double Fee { get; set; }

    public string? UserId { get; set; }
    public virtual IdentityUser User { get; set; }
}
