using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PADatabase.Models
{
    public  class Infromation
    {

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)] // Indicates that the value is generated by the database
        public Guid Id { get; set; }

        public string Message { get; set; }

        public String UserId { get; set; }

        public virtual UserPersonalDetails UserPersonalDetail { get; set; }
     
    }
}
