using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PADatabase.Models
{
    public class Location
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)] // Indicates that the value is generated by the database
        public Guid Id { get; set; }
        public string City { get; set; }

        public decimal Lat { get; set; }

        public decimal Lng { get; set; }

        public string Country { get; set; }

        public string Iso2 { get; set; }

        public string AdminName { get; set; }

        public string Capital { get; set; }

        public int Population { get; set; }

        public int PopulationProper { get; set; }
    }
}
